harmonyclub/config/routes.rb
Rails.application.routes.draw do
  namespace :web do
    get 'photos/index'
    get 'photos/show/:id', to: "photos#show", as: "albumPhoto"
    get 'events/calendar'
    get 'events/show'
  end
  get "pages/home", as: "home"
  get "pages/panel", as: "panel"
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  resources :sections
  
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

harmonyclub/app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="pages">
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :section_id, style: "display: block" %>
      <%= form.number_field :section_id %>
    </div>

    <div>
      <%= form.label :position, style: "display: block" %>
      <%= form.number_field :position %>
    </div>

    <div>
      <%= form.label :page_type, style: "display: block" %>
      <%= form.select :page_type,
            [" ", "Basic Page", "External URL", "Internal URL", "PDF"],
            {},
            data: {
              action: "change->pages#pageChange",
              "pages-target": "box"
            } %>
    </div>

    <div>
      <%= form.label :destination, style: "display: block" %>
      <%= form.text_field :destination %>
    </div>

    <div>
      <%= form.label :visible, style: "display: block" %>
      <%= form.check_box :visible %>
    </div>

    <div>
      <%= form.label :content, style: "display: block" %>
      <%= form.text_area :content %>
    </div>

    <div data-pages-target="fields">
      <p>test target one</p>
    </div>

    <div data-pages-target="fields">
      <p>test target two</p>
    </div>

    <div data-pages-target="fields">
      <p>test target three</p>
    </div>

    <div data-pages-target="fields">
      <p>test target four</p>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

harmonyclub/app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= page.section_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= page.position %>
  </p>

  <p>
    <strong>Page type:</strong>
    <%= page.page_type %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= page.destination %>
  </p>

  <p>
    <strong>Visible:</strong>
    <%= page.visible %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

</div>

harmonyclub/app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

harmonyclub/app/views/pages/home.html.erb
<div class="row">
    <div class="col text-center"><br>
        <%= image_tag "hcow_logo.png" %>
        <h1 class="masthead-heading text-uppercase mb-0">harmoney club woostah</h1>
        <div class="row">
            <div class="col col-md-4 p-4">
                <%= image_tag "merica_flag.gif", class: "img-fluid w-100" %>
            </div>
            <div class="col col-md-4 p-4">
                <%= image_tag "french_flag.gif", class: "img-fluid w-75" %>
            </div>
            <div class="col col-md-4 pe-5 pt-4">
                <%= image_tag "canada_flag.gif", class: "img-fluid w-100" %>
            </div>
        </div>
    </div>
</div>
<hr>
<p class="fs-6 fw-bold">The Harmony Club of Worcester, Massachusetts is a fraternal organization of men and women of French descent that was organized in 1925. 
The Club holds monthly meetings at O'Connor's Restaurant in Worcester with guest speakers. The Club also sponsors other cultural/social/sport events, tours, adult and children's 
Christmas parties. Members can participate in our golf league that takes place at Bed Rock Golf Club in Rutland, MA.</p>
<p class="fs-6 fw-bold">Our major fund raiser is our "Bob Picard Memorial Golf Tournament" that is held at the Leicester Country Club in Leicester, MA every September. 
The proceeds from this tournament are the sole funding of the scholarship and civic awards.</p>

harmonyclub/app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

harmonyclub/app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

harmonyclub/app/views/pages/panel.html.erb
<div class="row">
    <div class="col-12 space"></br></br></div>
</div>
<div class="row text-center"> 
    <div class="col col-lg-4">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Photo Album</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%= link_to "Photo Album", albums_path %>
            </div>
        </div>
    </div>
    <div class="col col-lg-4">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Events</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%= link_to "Events", events_path %>
            </div>
        </div>
    </div>
    <div class="col col-lg-4">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Pages</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%= link_to "Pages", pages_path %>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 space"></br></br></div>
</div>
<div class="row text-center">

    <div class="col col-lg-6">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Photos</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%= link_to "Photos", photos_path %>
            </div>
        </div>
    </div>
    <div class="col col-lg-6">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Sponsors</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%= link_to "Sponsors", sponsors_path %>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 space"></br></br></div>
</div>
<% if @user != nil && @user.dev %>
    <div class="row text-center">
        <div class="col col-lg-12">
            <div class="card mx-auto" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Sections</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <%= link_to "Sections", sections_path %>
                </div>
            </div>
        </div>
    </div>
<% end %>

harmonyclub/app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>